# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APBanner-Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform :ios, '8.0'
  # Pods for APBanner-Demo
  pod 'APBanner', '~> 1.0.1'
end
